Show similar posts list
pravintp/my-blog pull request #12
Opened 2021-12-06 08:23 UTC by pravintp

2021-12-10 09:34 UTC, waranlogesh requested changes

2021-12-10 09:34 UTC, waranlogesh commented on mysite/blog/utils.py
> +def get_similar_posts(post):
Should be part of post

2021-12-10 09:34 UTC, waranlogesh commented on mysite/blog/views.py
> +    similar_posts = get_similar_posts(post)
Not needed

2021-12-10 09:34 UTC, waranlogesh commented on mysite/blog/templates/blog/post/detail.html
> +  {% for post in similar_posts %}
get it from the post directly

2021-12-15 14:25 UTC, pravintp commented on mysite/blog/models.py
> +        )[:4]
simplify

2021-12-16 13:05 UTC, waranlogesh approved these changes

2021-12-16 13:45 UTC, merged